In [1]:
import pandas as pd

/Users/ailinhuang/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
file_path = "Data/2025 County Health Rankings Data - v1.xlsx"
sheet_name = "Select Measure Data"

In [3]:
# Read the full sheet while setting the multi-header structure
df = pd.read_excel(file_path, sheet_name=sheet_name, header=[0, 1])

In [4]:
df

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Premature Death  \
                   FIPS              State             County      Unreliable
0                  1000            Alabama                NaN             NaN
1                  1001            Alabama            Autauga             NaN
2                  1003            Alabama            Baldwin             NaN
3                  1005            Alabama            Barbour             NaN
4                  1007            Alabama               Bibb             NaN
...                 ...                ...                ...             ...
3205              56037            Wyoming         Sweetwater             NaN
3206              56039            Wyoming              Teton             NaN
3207              56041            Wyoming              Uinta             NaN
3208              56043            Wyoming           Washakie             NaN
3209              56045            Wyoming             Weston             NaN

                                                                              \
        Deaths Years of Potential Life Lost Rate  95% CI - Low 95% CI - High
0     102760.0                      11853.247248  11744.014820  11962.479676
1       1008.0                       9938.263382   9021.297133  10855.229632
2       3944.0                       8957.112686   8499.339223   9414.886148
3        587.0                      12738.656137  11133.499025  14343.813250
4        509.0                      11708.948038  10166.716823  13251.179253
...        ...                               ...           ...           ...
3205     710.0                      10209.647523   9151.477900  11267.817145
3206     123.0                       4173.600426   2994.859734   5352.341118
3207     339.0                      10947.029740   9257.388333  12636.671147
3208     130.0                       9591.275121   6806.979591  12375.570651
3209     101.0                       6754.810127   4512.108630   8997.511625

                                                        ...  \
     National Z-Score YPLL Rate (Hispanic (all races))  ...
0                 NaN                              NaN  ...
1           -0.144182                              NaN  ...
2           -0.400274                       4636.48424  ...
3            0.586752                              NaN  ...
4            0.317987                              NaN  ...
...               ...                              ...  ...
3205        -0.073348                       7150.40298  ...
3206        -1.648825                              NaN  ...
3207         0.119117                              NaN  ...
3208        -0.234750                              NaN  ...
3209        -0.975100                              NaN  ...

                                              Injury Deaths  \
     Injury Death Rate (Non-Hispanic 2+ races) 95% CI - Low
0                                                   NaN
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
3205                                                NaN
3206                                                NaN
3207                                                NaN
3208                                                NaN
3209                                                NaN

                                                              \
     Injury Death Rate (Non-Hispanic 2+ races) 95% CI - High
0                                                   NaN
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
3205                                                NaN
3206                                                NaN
3207                                                NaN
3208                                                NaN
3209                                                NaN

                                             \
     Injury Death Rate (Non-Hispanic White)
0                                       NaN
1                                 66.353516
2                                 86.954622
3                                 92.500356
4                                110.157489
...                                     ...
3205                             117.360350
3206                                    NaN
3207                                    NaN
3208                                    NaN
3209                                    NaN

                                                          \
     Injury Death Rate (Non-Hispanic White) 95% CI - Low
0                                                   NaN
1                                             55.322574
2                                             81.060141
3                                             69.083690
4                                             88.691939
...                                                 ...
3205                                         100.929901
3206                                                NaN
3207                                                NaN
3208                                                NaN
3209                                                NaN

                                                          Social Associations  \
     Injury Death Rate (Non-Hispanic White) 95% CI - High      # Associations
0                                                   NaN                5916.0
1                                             77.384459                  67.0
2                                             92.849104                 239.0
3                                            121.301910                  22.0
4                                            135.248986                  19.0
...                                                 ...                   ...
3205                                         133.790799                  33.0
3206                                                NaN                  48.0
3207                                                NaN                   6.0
3208                                                NaN                  12.0
3209                                                NaN                   8.0

                                               \
     Social Association Rate National Z-Score
0                  11.658760              NaN
1                  11.211700         0.043429
2                   9.698298         0.308739
3                   8.904720         0.447859
4                   8.634401         0.495248
...                      ...              ...
3205                7.981618         0.609686
3206               20.612359        -1.604573
3207                2.896871         1.501078
3208               15.546055        -0.716414
3209               11.661808        -0.035478

                                  Child Care Cost Burden
     % Household Income Required for Child Care Expenses National Z-Score
0                                             25.547114               NaN
1                                             21.835108         -0.961825
2                                             19.354057         -1.316051
3                                             28.579628          0.001105
4                                             26.582776         -0.283990
...                                                 ...               ...
3205                                          24.469532         -0.585703
3206                                          19.318356         -1.321148
3207                                          17.635233         -1.561451
3208                                          26.967545         -0.229056
3209                                          23.056195         -0.787488

[3210 rows x 225 columns]

In [5]:

# Concatenate multi-index columns to create unique headers
df.columns = [f"{str(col[0]).strip()} - {str(col[1]).strip()}" for col in df.columns]

# Display the first few rows to confirm structure
df.head()

,Unnamed: 0_level_0 - FIPS,Unnamed: 1_level_0 - State,Unnamed: 2_level_0 - County,Premature Death - Unreliable,Premature Death - Deaths,Premature Death - Years of Potential Life Lost Rate,Premature Death - 95% CI - Low,Premature Death - 95% CI - High,Premature Death - National Z-Score,Premature Death - YPLL Rate (Hispanic (all races)),...,Injury Deaths - Injury Death Rate (Non-Hispanic 2+ races) 95% CI - Low,Injury Deaths - Injury Death Rate (Non-Hispanic 2+ races) 95% CI - High,Injury Deaths - Injury Death Rate (Non-Hispanic White),Injury Deaths - Injury Death Rate (Non-Hispanic White) 95% CI - Low,Injury Deaths - Injury Death Rate (Non-Hispanic White) 95% CI - High,Social Associations - # Associations,Social Associations - Social Association Rate,Social Associations - National Z-Score,Child Care Cost Burden - % Household Income Required for Child Care Expenses,Child Care Cost Burden - National Z-Score
0,1000,Alabama,NaN,NaN,102760.0,11853.247248,11744.014820,11962.479676,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5916.0,11.658760,NaN,25.547114,NaN
1,1001,Alabama,Autauga,NaN,1008.0,9938.263382,9021.297133,10855.229632,-0.144182,NaN,...,NaN,NaN,66.353516,55.322574,77.384459,67.0,11.211700,0.043429,21.835108,-0.961825
2,1003,Alabama,Baldwin,NaN,3944.0,8957.112686,8499.339223,9414.886148,-0.400274,4636.48424,...,NaN,NaN,86.954622,81.060141,92.849104,239.0,9.698298,0.308739,19.354057,-1.316051
3,1005,Alabama,Barbour,NaN,587.0,12738.656137,11133.499025,14343.813250,0.586752,NaN,...,NaN,NaN,92.500356,69.083690,121.301910,22.0,8.904720,0.447859,28.579628,0.001105
4,1007,Alabama,Bibb,NaN,509.0,11708.948038,10166.716823,13251.179253,0.317987,NaN,...,NaN,NaN,110.157489,88.691939,135.248986,19.0,8.634401,0.495248,26.582776,-0.283990

In [6]:
column_names = list(df.columns)
column_names[:3] = ["FIPS", "State", "County"]
df.columns = column_names

In [7]:
df.columns

Index(['FIPS', 'State', 'County', 'Premature Death - Unreliable',
       'Premature Death - Deaths',
       'Premature Death - Years of Potential Life Lost Rate',
       'Premature Death - 95% CI - Low', 'Premature Death - 95% CI - High',
       'Premature Death - National Z-Score',
       'Premature Death - YPLL Rate (Hispanic (all races))',
       ...
       'Injury Deaths - Injury Death Rate (Non-Hispanic 2+ races) 95% CI - Low',
       'Injury Deaths - Injury Death Rate (Non-Hispanic 2+ races) 95% CI - High',
       'Injury Deaths - Injury Death Rate (Non-Hispanic White)',
       'Injury Deaths - Injury Death Rate (Non-Hispanic White) 95% CI - Low',
       'Injury Deaths - Injury Death Rate (Non-Hispanic White) 95% CI - High',
       'Social Associations - # Associations',
       'Social Associations - Social Association Rate',
       'Social Associations - National Z-Score',
       'Child Care Cost Burden - % Household Income Required for Child Care Expenses',
       'Child Care Cost Burden - National Z-Score'],
      dtype='object', length=225)

In [8]:
import re

# Keep original column names as descriptions
column_descriptions = df.columns.tolist()

# Create cleaned column names for BigQuery
cleaned_columns = []
for col in column_descriptions:
    # Replace special characters and patterns
    col_clean = col
    col_clean = re.sub(r'\s+', '_', col_clean)             # Replace spaces with underscores
    col_clean = col_clean.replace('#', 'count')            # Replace # with 'count'
    col_clean = col_clean.replace('%', 'pct')              # Replace % with 'pct'
    col_clean = col_clean.replace('2+', '2more')           # Replace '2+' with '2more'
    col_clean = re.sub(r'[()\-,]', '_', col_clean)         # Replace (, ), - and , with underscores
    col_clean = re.sub(r'__+', '_', col_clean)             # Collapse multiple underscores
    col_clean = col_clean.strip('_')                       # Remove leading/trailing underscores
    cleaned_columns.append(col_clean)

# Assign cleaned column names
df.columns = cleaned_columns

In [9]:
df

,FIPS,State,County,Premature_Death_Unreliable,Premature_Death_Deaths,Premature_Death_Years_of_Potential_Life_Lost_Rate,Premature_Death_95pct_CI_Low,Premature_Death_95pct_CI_High,Premature_Death_National_Z_Score,Premature_Death_YPLL_Rate_Hispanic_all_races,...,Injury_Deaths_Injury_Death_Rate_Non_Hispanic_2more_races_95pct_CI_Low,Injury_Deaths_Injury_Death_Rate_Non_Hispanic_2more_races_95pct_CI_High,Injury_Deaths_Injury_Death_Rate_Non_Hispanic_White,Injury_Deaths_Injury_Death_Rate_Non_Hispanic_White_95pct_CI_Low,Injury_Deaths_Injury_Death_Rate_Non_Hispanic_White_95pct_CI_High,Social_Associations_count_Associations,Social_Associations_Social_Association_Rate,Social_Associations_National_Z_Score,Child_Care_Cost_Burden_pct_Household_Income_Required_for_Child_Care_Expenses,Child_Care_Cost_Burden_National_Z_Score
0,1000,Alabama,NaN,NaN,102760.0,11853.247248,11744.014820,11962.479676,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5916.0,11.658760,NaN,25.547114,NaN
1,1001,Alabama,Autauga,NaN,1008.0,9938.263382,9021.297133,10855.229632,-0.144182,NaN,...,NaN,NaN,66.353516,55.322574,77.384459,67.0,11.211700,0.043429,21.835108,-0.961825
2,1003,Alabama,Baldwin,NaN,3944.0,8957.112686,8499.339223,9414.886148,-0.400274,4636.48424,...,NaN,NaN,86.954622,81.060141,92.849104,239.0,9.698298,0.308739,19.354057,-1.316051
3,1005,Alabama,Barbour,NaN,587.0,12738.656137,11133.499025,14343.813250,0.586752,NaN,...,NaN,NaN,92.500356,69.083690,121.301910,22.0,8.904720,0.447859,28.579628,0.001105
4,1007,Alabama,Bibb,NaN,509.0,11708.948038,10166.716823,13251.179253,0.317987,NaN,...,NaN,NaN,110.157489,88.691939,135.248986,19.0,8.634401,0.495248,26.582776,-0.283990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3205,56037,Wyoming,Sweetwater,NaN,710.0,10209.647523,9151.477900,11267.817145,-0.073348,7150.40298,...,NaN,NaN,117.360350,100.929901,133.790799,33.0,7.981618,0.609686,24.469532,-0.585703
3206,56039,Wyoming,Teton,NaN,123.0,4173.600426,2994.859734,5352.341118,-1.648825,NaN,...,NaN,NaN,NaN,NaN,NaN,48.0,20.612359,-1.604573,19.318356,-1.321148
3207,56041,Wyoming,Uinta,NaN,339.0,10947.029740,9257.388333,12636.671147,0.119117,NaN,...,NaN,NaN,NaN,NaN,NaN,6.0,2.896871,1.501078,17.635233,-1.561451
3208,56043,Wyoming,Washakie,NaN,130.0,9591.275121,6806.979591,12375.570651,-0.234750,NaN,...,NaN,NaN,NaN,NaN,NaN,12.0,15.546055,-0.716414,26.967545,-0.229056
3209,56045,Wyoming,Weston,NaN,101.0,6754.810127,4512.108630,8997.511625,-0.975100,NaN,...,NaN,NaN,NaN,NaN,NaN,8.0,11.661808,-0.035478,23.056195,-0.787488

In [14]:
# Display mapping of original to cleaned column names
column_mapping = pd.DataFrame({
    "Original Column Name": column_descriptions,
    "Cleaned Column Name": cleaned_columns
})

In [15]:
column_mapping

,Original Column Name,Cleaned Column Name
0,FIPS,FIPS
1,State,State
2,County,County
3,Premature Death - Unreliable,Premature_Death_Unreliable
4,Premature Death - Deaths,Premature_Death_Deaths
...,...,...
220,Social Associations - # Associations,Social_Associations_count_Associations
221,Social Associations - Social Association Rate,Social_Associations_Social_Association_Rate
222,Social Associations - National Z-Score,Social_Associations_National_Z_Score
223,Child Care Cost Burden - % Household Income Re...,Child_Care_Cost_Burden_pct_Household_Income_Re...
224,Child Care Cost Burden - National Z-Score,Child_Care_Cost_Burden_National_Z_Score